In [1]:
import numpy as np
import pandas as pd
from pandas import Series

subjects = ['國文', '英文', '數學', '地理', '歷史']

def countFails(s:Series):
    failSubjects = s[s < 60]
    count = failSubjects.count()
    
    return count

def main():
    scores = np.random.randint(50, 101, size=(50, 5))
    scores_df = pd.DataFrame(scores, columns=subjects, index=range(1, 51))

    scores_sum = scores_df.sum(axis=1)
    scores_average = scores_df.mean(axis=1)

    scores_df['總分'] = scores_sum
    scores_df['平均'] = scores_average

    scores_df['不及格的科目數'] = scores_df[subjects].apply(countFails, axis=1)

    display(scores_df)

main()

    國文  英文  數學   地理  歷史   總分    平均  不及格的科目數
1   59  56  79   86  82  362  72.4        2
2   80  51  65   74  56  326  65.2        2
3   83  91  62   57  98  391  78.2        1
4   55  96  55   50  92  348  69.6        3
5   91  75  88   89  70  413  82.6        0
6   95  53  94   91  73  406  81.2        1
7   96  79  64   54  90  383  76.6        1
8   61  95  69   85  99  409  81.8        0
9   79  96  93   52  92  412  82.4        1
10  57  98  56   80  83  374  74.8        2
11  90  78  78   83  73  402  80.4        0
12  80  81  95   58  94  408  81.6        1
13  91  64  61   53  63  332  66.4        1
14  54  59  52   73  77  315  63.0        3
15  81  94  92   72  78  417  83.4        0
16  98  86  98   91  76  449  89.8        0
17  91  84  63   73  73  384  76.8        0
18  87  53  50   68  87  345  69.0        2
19  53  80  57  100  85  375  75.0        2
20  68  89  77   61  79  374  74.8        0
21  75  98  50   73  66  362  72.4        1
22  92  78  73   68  66  377  75.4        0
23  68  77  67   98  60  370  74.0        0
24  65  67  88   76  93  389  77.8        0
25  90  50  76   61  58  335  67.0        2
26  96  57  77   50  77  357  71.4        2
27  80  92  64   64  51  351  70.2        1
28  78  50  57   55  56  296  59.2        4
29  61  80  67   98  83  389  77.8        0
30  84  64  98   83  53  382  76.4        1
31  76  51  89   74  63  353  70.6        1
32  64  97  85   97  52  395  79.0        1
33  67  92  66   64  54  343  68.6        1
34  78  79  73   77  65  372  74.4        0
35  80  64  57   50  77  328  65.6        2
36  95  60  98   67  62  382  76.4        0
37  86  66  90   55  54  351  70.2        2
38  53  77  69   92  70  361  72.2        1
39  50  92  84   53  61  340  68.0        2
40  71  84  69   59  66  349  69.8        1
41  78  74  82   94  65  393  78.6        0
42  89  57  55   91  97  389  77.8        2
43  84  99  87   79  56  405  81.0        1
44  95  94  62   90  59  400  80.0        1
45  60  54  53   84  75  326  65.2        2
46  50  56  70   92  50  318  63.6        3
47  74  99  70   76  89  408  81.6        0
48  94  61  96   58  95  404  80.8        1
49  83  88  72   56  79  378  75.6        1
50  94  79  68   53  70  364  72.8        1